from sockets import wsgi


request = {'TERM_PROGRAM': 'Apple_Terminal', 'PYENV_ROOT': '/Users/blazej/.pyenv', 'TERM': 'xterm-256color', 'SHELL': '/usr/local/bin/fish', 'TERM_PROGRAM_VERSION': '433', 'TERM_SESSION_ID': 'F88EE211-13C9-4607-9816-BEE34480F370', 'PYENV_VERSION': '3.7.3', 'USER': 'blazej', 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.wVCifycv37/Listeners', 'PYENV_DIR': '/Users/blazej/workspace/web_sockets/sockets', 'PYENV_VIRTUALENV_INIT': '1', 'PATH': '/Users/blazej/.pyenv/versions/3.7.3/bin:/Users/blazej/.pyenv/libexec:/Users/blazej/.pyenv/plugins/python-build/bin:/Users/blazej/.pyenv/plugins/pyenv-virtualenv/bin:/Users/blazej/.pyenv/plugins/pyenv-update/bin:/Users/blazej/.pyenv/plugins/pyenv-installer/bin:/Users/blazej/.pyenv/plugins/pyenv-doctor/bin:/Users/blazej/.pyenv/plugins/pyenv-virtualenv/shims:/Users/blazej/.pyenv/shims:/Users/blazej/.pyenv/bin:/Applications/Sublime Text.app/Contents/SharedSupport/bin/:/Applications/Sublime Merge.app/Contents/SharedSupport/bin/:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin', 'LaunchInstanceID': '2A157E99-F669-47C4-972B-D3ED2CB16669', 'PWD': '/Users/blazej/workspace/web_sockets/sockets', 'LANG': 'en_GB.UTF-8', 'PYENV_HOOK_PATH': '/Users/blazej/.pyenv/pyenv.d:/usr/local/etc/pyenv.d:/etc/pyenv.d:/usr/lib/pyenv/hooks:/Users/blazej/.pyenv/plugins/pyenv-virtualenv/etc/pyenv.d:/Users/blazej/.pyenv/plugins/pyenv-which-ext/etc/pyenv.d', 'XPC_FLAGS': '0x0', 'XPC_SERVICE_NAME': '0', 'SHLVL': '1', 'PYENV_SHELL': 'fish', 'HOME': '/Users/blazej', 'LOGNAME': 'blazej', 'SECURITYSESSIONID': '186a6', '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x2', 'DJANGO_SETTINGS_MODULE': 'sockets.settings', 'TZ': 'UTC', 'RUN_MAIN': 'true', 'SERVER_NAME': '1.0.0.127.in-addr.arpa', 'GATEWAY_INTERFACE': 'CGI/1.1', 'SERVER_PORT': '8000', 'REMOTE_HOST': '', 'CONTENT_LENGTH': '', 'SCRIPT_NAME': '', 'SERVER_PROTOCOL': 'HTTP/1.1', 'SERVER_SOFTWARE': 'WSGIServer/0.2', 'REQUEST_METHOD': 'GET', 'PATH_INFO': '/', 'QUERY_STRING': '', 'REMOTE_ADDR': '127.0.0.1', 'CONTENT_TYPE': 'text/plain', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:78.0) Gecko/20100101 Firefox/78.0', 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'HTTP_ACCEPT_LANGUAGE': 'en-GB,en;q=0.5', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate', 'HTTP_DNT': '1', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_UPGRADE_INSECURE_REQUESTS': '1', 'HTTP_PRAGMA': 'no-cache', 'HTTP_CACHE_CONTROL': 'no-cache', 'wsgi.input': None}

def noop(status, headers):
    pass

response = wsgi.application(request, noop)
print(response)
#print(response.content)